name: notebooks2020
channels:
  - anaconda
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bioconductor-affxparser=1.60.0
  - bioconductor-affyio=1.58.0
  - bioconductor-biobase=2.48.0
  - bioconductor-biocgenerics=0.34.0
  - bioconductor-biostrings=2.56.0
  - bioconductor-delayedarray=0.14.0
  - bioconductor-genomeinfodb=1.24.0
  - bioconductor-genomeinfodbdata=1.2.3
  - bioconductor-genomicranges=1.40.0
  - bioconductor-geoquery=2.56.0
  - bioconductor-iranges=2.22.1
  - bioconductor-limma=3.44.1
  - bioconductor-oligo=1.52.0
  - bioconductor-oligoclasses=1.50.0
  - bioconductor-preprocesscore=1.50.0
  - bioconductor-s4vectors=0.26.0
  - bioconductor-summarizedexperiment=1.18.1
  - bioconductor-xvector=0.28.0
  - bioconductor-zlibbioc=1.34.0
  - bleach=3.1.5
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cairo=1.16.0
  - cctools=927.0.2
  - certifi=2020.4.5.1
  - clang=10.0.0
  - clang-tools=10.0.0
  - clang_osx-64=10.0.0
  - clangxx=10.0.0
  - clangxx_osx-64=10.0.0
  - compiler-rt=10.0.0
  - compiler-rt_osx-64=10.0.0
  - curl=7.69.1
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - fribidi=1.0.9
  - gettext=0.19.8.1
  - gfortran_impl_osx-64=7.3.0
  - gfortran_osx-64=7.3.0
  - glib=2.64.3
  - gmp=6.2.0
  - graphite2=1.3.13
  - gsl=2.6
  - harfbuzz=2.4.0
  - icu=64.2
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.3.0
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isl=0.19
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - krb5=1.17.1
  - ld64=450.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm10=10.0.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libsodium=1.0.17
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - llvm-tools=10.0.0
  - llvmdev=10.0.0
  - lz4-c=1.9.2
  - make=4.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - notebook=6.0.3
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.0
  - pcre=8.44
  - pcre2=10.34
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - pixman=0.38.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - r=4.0
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.7
  - r-base=4.0.0
  - r-biocmanager=1.30.10
  - r-bit=1.1_15.2
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-boot=1.3_25
  - r-class=7.3_17
  - r-cli=2.0.2
  - r-clipr=0.7.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-dbi=1.1.0
  - r-digest=0.6.25
  - r-dplyr=0.8.5
  - r-ellipsis=0.3.1
  - r-fansi=0.4.1
  - r-ff=2.2_14.2
  - r-foreach=1.5.0
  - r-foreign=0.8_80
  - r-glue=1.4.1
  - r-hms=0.5.3
  - r-httr=1.4.1
  - r-iterators=1.0.12
  - r-jsonlite=1.6.1
  - r-kernsmooth=2.23_17
  - r-lattice=0.20_41
  - r-lifecycle=0.2.0
  - r-magrittr=1.5
  - r-mass=7.3_51.6
  - r-matrix=1.2_18
  - r-matrixstats=0.56.0
  - r-memoise=1.1.0
  - r-mgcv=1.8_31
  - r-mime=0.9
  - r-nlme=3.1_148
  - r-nnet=7.3_14
  - r-openssl=1.4.1
  - r-pillar=1.4.4
  - r-pkgconfig=2.0.3
  - r-plogr=0.2.0
  - r-purrr=0.3.4
  - r-r6=2.4.1
  - r-rcpp=1.0.4.6
  - r-rcurl=1.98_1.2
  - r-readr=1.3.1
  - r-recommended=4.0
  - r-rlang=0.4.6
  - r-rpart=4.1_15
  - r-rsqlite=2.2.0
  - r-spatial=7.3_12
  - r-stringi=1.4.6
  - r-survival=3.1_12
  - r-sys=3.3
  - r-tibble=3.0.1
  - r-tidyr=1.1.0
  - r-tidyselect=1.1.0
  - r-utf8=1.1.4
  - r-vctrs=0.3.0
  - r-xml2=1.3.2
  - r-zeallot=0.1.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.31.1
  - tapi=1000.10.8
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4

